# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_phylogenysort_wrappers", use_symbols = TRUE, package_name = "phylogenysort")

#' @usage NULL
#' @useDynLib phylogenysort, .registration = TRUE
NULL

tree_sort_alphabetical <- function(x) .Call(wrap__tree_sort_alphabetical, x)


# nolint end
